import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { authUserSession } from "./libs/auth-libs";
const inter = Inter({ subsets: ["latin"] });
import { SessionProvider } from "next-auth/react";
import NextAuthProvider from "./NextAuthProvider";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Link href="/api/auth/signin">test</Link>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
